name: Semantic release 

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install 
      - name: Run tests
        run: yarn test
      - name: Generate Build Id
        id: BUILD_ID
        run: echo "::set-output name=BUILD_ID::$(git rev-parse --short HEAD)"
      - name: Build app
        env:
          NEXT_PUBLIC_BUILD_ID: ${{ steps.BUILD_ID.outputs.BUILD_ID }}
        run: yarn build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release